syntax = "proto3";
package pb;
option go_package = "gim-xchat/pkg/protocol/pb";

import "google/protobuf/empty.proto";

service LogicExt {
  // 注册设备
  rpc RegisterDevice (RegisterDeviceReq) returns (RegisterDeviceResp);

  // 推送消息到房间
  rpc PushRoom(PushRoomReq)returns(google.protobuf.Empty);

  // 发送好友消息
  rpc SendMessageToFriend (SendMessageReq) returns (SendMessageResp);
  // 添加好友
  rpc AddFriend (AddFriendReq) returns (google.protobuf.Empty);
  // 同意添加好友
  rpc AgreeAddFriend (AgreeAddFriendReq) returns (google.protobuf.Empty);
  // 设置好友信息
  rpc SetFriend (SetFriendReq) returns (SetFriendResp);
  // 获取好友列表
  rpc GetFriends (google.protobuf.Empty) returns (GetFriendsResp);

  // 发送群组消息
  rpc SendMessageToGroup (SendMessageReq) returns (SendMessageResp);
  // 创建群组
  rpc CreateGroup (CreateGroupReq) returns (CreateGroupResp);
  // 更新群组
  rpc UpdateGroup (UpdateGroupReq) returns (google.protobuf.Empty);
  // 获取群组信息
  rpc GetGroup (GetGroupReq) returns (GetGroupResp);
  // 获取用户加入的所有群组
  rpc GetGroups (google.protobuf.Empty) returns (GetGroupsResp);

  // 添加群组成员
  rpc AddGroupMembers (AddGroupMembersReq) returns (AddGroupMembersResp);
  // 更新群组成员信息
  rpc UpdateGroupMember (UpdateGroupMemberReq) returns (google.protobuf.Empty);
  // 添加群组成员
  rpc DeleteGroupMember (DeleteGroupMemberReq) returns (google.protobuf.Empty);
  // 获取群组成员
  rpc GetGroupMembers (GetGroupMembersReq) returns (GetGroupMembersResp);
  // 创建聊天室
  rpc CreateChatRoom (CreateChatRoomReq) returns (CreateChatRoomResp);
  // 获取聊天室信息
  rpc GetChatRoom (GetChatRoomReq) returns (GetChatRoomResp);
  // 获取聊天室列表
  rpc GetChatRooms (GetChatRoomsReq) returns (GetChatRoomsResp);
  // 加入聊天室
  rpc JoinChatRoom (JoinChatRoomReq) returns (google.protobuf.Empty);
  // 离开聊天室
  rpc LeaveChatRoom (LeaveChatRoomReq) returns (google.protobuf.Empty);
  // 获取聊天室成员
  rpc GetChatRoomMembers (GetChatRoomMembersReq) returns (GetChatRoomMembersResp);
  // 发送聊天室消息
  rpc SendChatRoomMessage (SendChatRoomMessageReq) returns (SendChatRoomMessageResp);
  // 获取聊天室消息历史
  rpc GetChatRoomMessages (GetChatRoomMessagesReq) returns (GetChatRoomMessagesResp);
  // 获取用户加入的聊天室列表
  rpc GetUserChatRooms (GetUserChatRoomsReq) returns (GetUserChatRoomsResp);
  // 获取用户创建的聊天室列表
  rpc GetUserCreatedChatRooms (GetUserCreatedChatRoomsReq) returns (GetUserCreatedChatRoomsResp);
}
message GetUserChatRoomsReq {
  int32 page_size = 1;  // 每页数量
  int32 page_number = 2; // 偏移量
}

message GetUserChatRoomsResp {
  repeated ChatRoom chat_rooms = 1; // 聊天室列表
  int32 total = 2;                  // 总数
}

message GetUserCreatedChatRoomsReq {
  int64 user_id = 1;
}

message GetUserCreatedChatRoomsResp {
  repeated ChatRoom chat_rooms = 1;
}

message RegisterDeviceReq {
  int32 type = 2; // 设备类型
  string brand = 3; // 厂商
  string model = 4; // 机型
  string system_version = 5; // 系统版本
  string sdk_version = 6; // sdk版本号
}
message RegisterDeviceResp {
  int64 device_id = 1; // 设备id
}

message SendMessageReq {
  int64 receiver_id = 1; // 接收者ID，用户ID/群组ID
  bytes content = 2; // 推动内容
  int64 send_time = 3; // 消息发送时间戳，精确到毫秒
}
message SendMessageResp {
  int64 seq = 1; // 消息序列号
}

message PushRoomReq{
  int64 room_id = 1; // 房间id
  int32 code = 2; // 消息类型
  bytes content = 3; // 消息内容
  int64 send_time = 4; // 消息发送时间戳，精确到毫秒
  bool is_persist = 5; // 是否将消息持久化
  bool is_priority = 6; // 是否优先推送
}

message AddFriendReq {
  int64 friend_id = 1; // 用户id
  string remarks = 2; // 备注
  string description = 3; // 描述
}

message AgreeAddFriendReq {
  int64 user_id = 1; // 用户id
  string remarks = 2; // 备注
}

message SetFriendReq {
  int64 friend_id = 1; // 好友id
  string remarks = 2; // 备注
  string extra = 8; // 附加字段
}
message SetFriendResp {
  int64 friend_id = 1; // 好友id
  string remarks = 2; // 备注
  string extra = 8; // 附加字段
}

message Friend {
  int64 user_id = 1; // 用户id
  string phone_number = 2; // 电话号码
  string nickname = 3; // 昵称
  int32 sex = 4; // 性别
  string avatar_url = 5; // 头像地址
  string user_extra = 6; // 用户附加字段
  string remarks = 7; // 备注
  string extra = 8; // 附加字段
}
message GetFriendsResp {
  repeated Friend friends = 1;
}

message CreateGroupReq {
  string name = 1; // 名称
  string avatar_url = 2; // 头像
  string introduction = 3; // 简介
  string extra = 4; // 附加字段
  repeated int64 member_ids = 5; // 群组成员ID列表
}
message CreateGroupResp {
  int64 group_id = 1; // 群组id
}

message UpdateGroupReq {
  int64 group_id = 1; // 群组id
  string avatar_url = 2; // 头像
  string name = 3; // 名称
  string introduction = 4; // 简介
  string extra = 5; // 附加字段
}

message GetGroupReq {
  int64 group_id = 1;
}
message GetGroupResp {
  Group group = 1;
}

message Group {
  int64 group_id = 1; // 群组id
  string name = 2; // 名称
  string avatar_url = 3; // 头像
  string introduction = 4; // 简介
  int32 user_mum = 5; // 用户数
  string extra = 6; // 附加字段
  int64 create_time = 7; // 创建时间
  int64 update_time = 8; // 更新时间
}

message GetGroupsResp {
  repeated Group groups = 1;
}

message AddGroupMembersReq {
  int64 group_id = 1; // 群组id
  repeated int64 user_ids = 2; // 用户id列表
}
message AddGroupMembersResp {
  repeated int64 user_ids = 1; // 已经在群组的用户id列表
}

enum MemberType {
  GMT_UNKNOWN = 0; // 未知
  GMT_ADMIN = 1; // 管理员
  GMT_MEMBER = 2; // 成员
}

message UpdateGroupMemberReq {
  int64 group_id = 1; // 群组id
  int64 user_id = 2; // 用户id
  MemberType member_type = 3; // 成员类型
  string remarks = 4; // 备注
  string extra = 5; // 附加字段
}

message DeleteGroupMemberReq {
  int64 group_id = 1; // 群组id
  int64 user_id = 2; // 用户id
}

message GetGroupMembersReq {
  int64 group_id = 1;
}
message GetGroupMembersResp {
  repeated GroupMember members = 1;
}
message GroupMember {
  int64 user_id = 1;
  string nickname = 2; // 昵称
  int32 sex = 3; // 性别
  string avatar_url = 4; // 头像地址
  string user_extra = 5; // 用户附加字段
  MemberType member_type = 6; // 成员类型
  string remarks = 7; // 备注
  string extra = 8; // 群组成员附加字段
}

message CreateChatRoomReq {
  string name = 1; // 聊天室名称
  string avatar_url = 2; // 聊天室头像
  string introduction = 3; // 聊天室简介
  string extra = 4; // 附加字段
  int32 max_member_count = 5; // 最大成员数量
}

message CreateChatRoomResp {
  int64 room_id = 1; // 聊天室ID
}

message GetChatRoomReq {
  int64 room_id = 1; // 聊天室ID
}

message GetChatRoomResp {
  ChatRoom room = 1; // 聊天室信息
}

message GetChatRoomsReq {
  int32 page_size = 1; // 每页大小
  int32 page_number = 2; // 页码
}

message GetChatRoomsResp {
  repeated ChatRoom rooms = 1; // 聊天室列表
  int32 total = 2; // 总数
}

message ChatRoom { 
   int64 room_id = 1; // 聊天室ID 
   string name = 2; // 名称 
   string avatar_url = 3; // 头像 
   string introduction = 4; // 简介 
   int32 online_count = 5; // 在线人数 
   int32 member_count = 6; // 成员总数 
   int32 max_member_count = 7; // 最大成员数量 
   string extra = 8; // 附加字段 
   int64 create_time = 9; // 创建时间 
   int64 update_time = 10; // 更新时间 
   int64 creator_id = 11; // 创建者ID
 } 

message JoinChatRoomReq {
  int64 room_id = 1; // 聊天室ID
}

message LeaveChatRoomReq {
  int64 room_id = 1; // 聊天室ID
}

message GetChatRoomMembersReq {
  int64 room_id = 1; // 聊天室ID
  int32 page_size = 2; // 每页大小
  int32 page_number = 3; // 页码
}

message GetChatRoomMembersResp {
  repeated ChatRoomMember members = 1; // 成员列表
  int32 total = 2; // 总数
}

message ChatRoomMember {
  int64 room_id = 1;    // 聊天室ID
  int64 user_id = 2;    // 用户ID
  string nickname = 3;   // 昵称
  string avatar_url = 4; // 头像
  int64 join_time = 5;   // 加入时间
  int32 status = 7;      // 状态 1:正常
}

message SendChatRoomMessageReq {
  int64 room_id = 1; // 聊天室ID
  int64 user_id = 2; // 发送者ID
  bytes content = 3; // 消息内容
  int64 send_time = 4; // 发送时间
}

message SendChatRoomMessageResp {
  int64 seq = 1; // 消息序列号
}

message ChatRoomMessageData {
    int64 sender_id = 1;    // 发送者ID
    string sender_name = 2; // 发送者昵称
    bytes content = 3;      // 消息内容
}

message ChatRoomMessage {
    int64 id = 1;          // 消息ID
    int64 room_id = 2;     // 聊天室ID
    int64 user_id = 3;     // 发送者ID
    int64 request_id = 4;  // 请求ID
    int32 code = 5;        // 消息类型
    bytes content = 6;     // 消息内容
    int64 seq = 7;         // 消息序列号
    int64 send_time = 8;   // 发送时间
    int32 status = 9;      // 消息状态
}

message GetChatRoomMessagesReq {
    int64 room_id = 1;     // 聊天室ID
    int32 page_size = 2;   // 每页数量
    int32 page_number = 3; // 页码
}

message GetChatRoomMessagesResp {
    repeated ChatRoomMessage messages = 1; // 消息列表
    int32 total = 2;                       // 总数
}