// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: business.int.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      int64                  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_business_int_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_int_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_business_int_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthReq) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *AuthReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       map[int64]int32        `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersReq) Reset() {
	*x = GetUsersReq{}
	mi := &file_business_int_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReq) ProtoMessage() {}

func (x *GetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_int_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReq.ProtoReflect.Descriptor instead.
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return file_business_int_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersReq) GetUserIds() map[int64]int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*User        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResp) Reset() {
	*x = GetUsersResp{}
	mi := &file_business_int_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResp) ProtoMessage() {}

func (x *GetUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_int_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResp.ProtoReflect.Descriptor instead.
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return file_business_int_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersResp) GetUsers() map[int64]*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_business_int_proto protoreflect.FileDescriptor

const file_business_int_proto_rawDesc = "" +
	"\n" +
	"\x12business.int.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12business.ext.proto\"U\n" +
	"\aAuthReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x03R\bdeviceId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x82\x01\n" +
	"\vGetUsersReq\x127\n" +
	"\buser_ids\x18\x01 \x03(\v2\x1c.pb.GetUsersReq.UserIdsEntryR\auserIds\x1a:\n" +
	"\fUserIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x85\x01\n" +
	"\fGetUsersResp\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.pb.GetUsersResp.UsersEntryR\x05users\x1aB\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x1e\n" +
	"\x05value\x18\x02 \x01(\v2\b.pb.UserR\x05value:\x028\x012\x95\x01\n" +
	"\vBusinessInt\x12+\n" +
	"\x04Auth\x12\v.pb.AuthReq\x1a\x16.google.protobuf.Empty\x12*\n" +
	"\aGetUser\x12\x0e.pb.GetUserReq\x1a\x0f.pb.GetUserResp\x12-\n" +
	"\bGetUsers\x12\x0f.pb.GetUsersReq\x1a\x10.pb.GetUsersRespB\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_business_int_proto_rawDescOnce sync.Once
	file_business_int_proto_rawDescData []byte
)

func file_business_int_proto_rawDescGZIP() []byte {
	file_business_int_proto_rawDescOnce.Do(func() {
		file_business_int_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_int_proto_rawDesc), len(file_business_int_proto_rawDesc)))
	})
	return file_business_int_proto_rawDescData
}

var file_business_int_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_business_int_proto_goTypes = []any{
	(*AuthReq)(nil),       // 0: pb.AuthReq
	(*GetUsersReq)(nil),   // 1: pb.GetUsersReq
	(*GetUsersResp)(nil),  // 2: pb.GetUsersResp
	nil,                   // 3: pb.GetUsersReq.UserIdsEntry
	nil,                   // 4: pb.GetUsersResp.UsersEntry
	(*User)(nil),          // 5: pb.User
	(*GetUserReq)(nil),    // 6: pb.GetUserReq
	(*emptypb.Empty)(nil), // 7: google.protobuf.Empty
	(*GetUserResp)(nil),   // 8: pb.GetUserResp
}
var file_business_int_proto_depIdxs = []int32{
	3, // 0: pb.GetUsersReq.user_ids:type_name -> pb.GetUsersReq.UserIdsEntry
	4, // 1: pb.GetUsersResp.users:type_name -> pb.GetUsersResp.UsersEntry
	5, // 2: pb.GetUsersResp.UsersEntry.value:type_name -> pb.User
	0, // 3: pb.BusinessInt.Auth:input_type -> pb.AuthReq
	6, // 4: pb.BusinessInt.GetUser:input_type -> pb.GetUserReq
	1, // 5: pb.BusinessInt.GetUsers:input_type -> pb.GetUsersReq
	7, // 6: pb.BusinessInt.Auth:output_type -> google.protobuf.Empty
	8, // 7: pb.BusinessInt.GetUser:output_type -> pb.GetUserResp
	2, // 8: pb.BusinessInt.GetUsers:output_type -> pb.GetUsersResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_business_int_proto_init() }
func file_business_int_proto_init() {
	if File_business_int_proto != nil {
		return
	}
	file_business_ext_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_int_proto_rawDesc), len(file_business_int_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_int_proto_goTypes,
		DependencyIndexes: file_business_int_proto_depIdxs,
		MessageInfos:      file_business_int_proto_msgTypes,
	}.Build()
	File_business_int_proto = out.File
	file_business_int_proto_goTypes = nil
	file_business_int_proto_depIdxs = nil
}
