// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: business.ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息，包含 walletAddress 参数
type GetTwitterAuthorizeURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // 钱包地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTwitterAuthorizeURLReq) Reset() {
	*x = GetTwitterAuthorizeURLReq{}
	mi := &file_business_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTwitterAuthorizeURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwitterAuthorizeURLReq) ProtoMessage() {}

func (x *GetTwitterAuthorizeURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwitterAuthorizeURLReq.ProtoReflect.Descriptor instead.
func (*GetTwitterAuthorizeURLReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{0}
}

func (x *GetTwitterAuthorizeURLReq) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// 钱包登录请求
type WalletSignInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // 钱包地址 (如以太坊地址)
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                              // 签名数据 (用户用钱包签名的身份验证信息)
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                  // 原始消息 (可以是时间戳、nonce等，用于防止重放攻击)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletSignInReq) Reset() {
	*x = WalletSignInReq{}
	mi := &file_business_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletSignInReq) ProtoMessage() {}

func (x *WalletSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletSignInReq.ProtoReflect.Descriptor instead.
func (*WalletSignInReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{1}
}

func (x *WalletSignInReq) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *WalletSignInReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WalletSignInReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 钱包登录响应
type WalletSignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                        // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // 消息描述
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`         // 是否是新用户
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`                       // Token (返回给客户端用于后续请求)
	UserInfo      *User                  `protobuf:"bytes,6,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletSignInResp) Reset() {
	*x = WalletSignInResp{}
	mi := &file_business_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletSignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletSignInResp) ProtoMessage() {}

func (x *WalletSignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletSignInResp.ProtoReflect.Descriptor instead.
func (*WalletSignInResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{2}
}

func (x *WalletSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WalletSignInResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WalletSignInResp) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *WalletSignInResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WalletSignInResp) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 修改任务状态请求
type ModifyTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`               // 任务状态 (1: 未完成, 2: 进行中, 3: 待领取, 4: 已领取)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyTaskStatusReq) Reset() {
	*x = ModifyTaskStatusReq{}
	mi := &file_business_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTaskStatusReq) ProtoMessage() {}

func (x *ModifyTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTaskStatusReq.ProtoReflect.Descriptor instead.
func (*ModifyTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyTaskStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModifyTaskStatusReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ModifyTaskStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 修改任务状态响应
type ModifyTaskStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyTaskStatusResp) Reset() {
	*x = ModifyTaskStatusResp{}
	mi := &file_business_ext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyTaskStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTaskStatusResp) ProtoMessage() {}

func (x *ModifyTaskStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTaskStatusResp.ProtoReflect.Descriptor instead.
func (*ModifyTaskStatusResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyTaskStatusResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyTaskStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 登录请求
type SignInReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                  // 验证码
	DeviceId      int64                  `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`         // 设备ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInReq) Reset() {
	*x = SignInReq{}
	mi := &file_business_ext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInReq) ProtoMessage() {}

func (x *SignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInReq.ProtoReflect.Descriptor instead.
func (*SignInReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{5}
}

func (x *SignInReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SignInReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SignInReq) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

// 登录响应
type SignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsNew         bool                   `protobuf:"varint,1,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`    // 是否是新用户
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                  // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResp) Reset() {
	*x = SignInResp{}
	mi := &file_business_ext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResp) ProtoMessage() {}

func (x *SignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResp.ProtoReflect.Descriptor instead.
func (*SignInResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{6}
}

func (x *SignInResp) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *SignInResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 用户信息
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // 用户id
	Nickname        string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                                      // 昵称
	Sex             int32                  `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`                                               // 性别
	AvatarUrl       string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                   // 头像地址
	Extra           string                 `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`                                            // 附加字段
	CreateTime      int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`               // 创建时间
	UpdateTime      int64                  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`               // 更新时间
	TwitterId       string                 `protobuf:"bytes,8,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`                   // 推特id
	TwitterUsername string                 `protobuf:"bytes,9,opt,name=twitter_username,json=twitterUsername,proto3" json:"twitter_username,omitempty"` // 推特用户名
	Xpoint          float64                `protobuf:"fixed64,10,opt,name=xpoint,proto3" json:"xpoint,omitempty"`                                       // 用户当前积分
	FollowReward    int32                  `protobuf:"varint,11,opt,name=follow_reward,json=followReward,proto3" json:"follow_reward,omitempty"`        // Twitter关注奖励状态: 0未领取, 1已领取
	InviteCode      string                 `protobuf:"bytes,12,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`               // 邀请码
	InviterCode     string                 `protobuf:"bytes,13,opt,name=inviter_code,json=inviterCode,proto3" json:"inviter_code,omitempty"`            // 邀请人邀请码
	WalletAddress   string                 `protobuf:"bytes,14,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`      // 钱包地址
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_business_ext_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *User) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *User) GetTwitterId() string {
	if x != nil {
		return x.TwitterId
	}
	return ""
}

func (x *User) GetTwitterUsername() string {
	if x != nil {
		return x.TwitterUsername
	}
	return ""
}

func (x *User) GetXpoint() float64 {
	if x != nil {
		return x.Xpoint
	}
	return 0
}

func (x *User) GetFollowReward() int32 {
	if x != nil {
		return x.FollowReward
	}
	return 0
}

func (x *User) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *User) GetInviterCode() string {
	if x != nil {
		return x.InviterCode
	}
	return ""
}

func (x *User) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// 获取用户信息请求
type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_business_ext_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户信息响应
type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_business_ext_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 更新用户信息请求
type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	Sex           int32                  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`                             // 性别
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像地址
	Extra         string                 `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`                          // 附加字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_business_ext_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UpdateUserReq) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// 搜索用户请求
type SearchUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 搜索关键字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserReq) Reset() {
	*x = SearchUserReq{}
	mi := &file_business_ext_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserReq) ProtoMessage() {}

func (x *SearchUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserReq.ProtoReflect.Descriptor instead.
func (*SearchUserReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{11}
}

func (x *SearchUserReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 搜索用户响应
type SearchUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserResp) Reset() {
	*x = SearchUserResp{}
	mi := &file_business_ext_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserResp) ProtoMessage() {}

func (x *SearchUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserResp.ProtoReflect.Descriptor instead.
func (*SearchUserResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{12}
}

func (x *SearchUserResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// 获取 Twitter 授权 URL 响应
type TwitterAuthorizeURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`         // 授权 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwitterAuthorizeURLResp) Reset() {
	*x = TwitterAuthorizeURLResp{}
	mi := &file_business_ext_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterAuthorizeURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterAuthorizeURLResp) ProtoMessage() {}

func (x *TwitterAuthorizeURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterAuthorizeURLResp.ProtoReflect.Descriptor instead.
func (*TwitterAuthorizeURLResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{13}
}

func (x *TwitterAuthorizeURLResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TwitterAuthorizeURLResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TwitterAuthorizeURLResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 推特登录请求
type TwitterSignInReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode string                 `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"` // 授权码
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                                  // 状态
	WalletAddress     string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`             // 钱包地址
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TwitterSignInReq) Reset() {
	*x = TwitterSignInReq{}
	mi := &file_business_ext_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterSignInReq) ProtoMessage() {}

func (x *TwitterSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterSignInReq.ProtoReflect.Descriptor instead.
func (*TwitterSignInReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{14}
}

func (x *TwitterSignInReq) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *TwitterSignInReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TwitterSignInReq) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// 推特登录响应
type TwitterSignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                        // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // 消息描述
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`         // 是否是新用户
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户ID
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`                       // Token
	UserInfo      *User                  `protobuf:"bytes,6,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"` // 用户信息
	ErrMessage    string                 `protobuf:"bytes,7,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	RoomId        int64                  `protobuf:"varint,8,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 用户创建的聊天室ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwitterSignInResp) Reset() {
	*x = TwitterSignInResp{}
	mi := &file_business_ext_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterSignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterSignInResp) ProtoMessage() {}

func (x *TwitterSignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterSignInResp.ProtoReflect.Descriptor instead.
func (*TwitterSignInResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{15}
}

func (x *TwitterSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TwitterSignInResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TwitterSignInResp) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *TwitterSignInResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TwitterSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TwitterSignInResp) GetUserInfo() *User {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *TwitterSignInResp) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

func (x *TwitterSignInResp) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 每日签到响应
type DailySignInResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySignInResp) Reset() {
	*x = DailySignInResp{}
	mi := &file_business_ext_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySignInResp) ProtoMessage() {}

func (x *DailySignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySignInResp.ProtoReflect.Descriptor instead.
func (*DailySignInResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{16}
}

func (x *DailySignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DailySignInResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Twitter 关注奖励响应
type TwitterFollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`       // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息描述
	Success       int32                  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // 领取状态 (0: 失败, 1: 成功)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwitterFollowResp) Reset() {
	*x = TwitterFollowResp{}
	mi := &file_business_ext_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterFollowResp) ProtoMessage() {}

func (x *TwitterFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterFollowResp.ProtoReflect.Descriptor instead.
func (*TwitterFollowResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{17}
}

func (x *TwitterFollowResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TwitterFollowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TwitterFollowResp) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

// 查询任务状态请求
type GetTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusReq) Reset() {
	*x = GetTaskStatusReq{}
	mi := &file_business_ext_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusReq) ProtoMessage() {}

func (x *GetTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusReq.ProtoReflect.Descriptor instead.
func (*GetTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{18}
}

func (x *GetTaskStatusReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// 查询任务状态响应
type GetTaskStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`  // 任务状态 (1: 未完成, 2: 进行中, 3: 待领取, 4: 已领取)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResp) Reset() {
	*x = GetTaskStatusResp{}
	mi := &file_business_ext_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResp) ProtoMessage() {}

func (x *GetTaskStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResp.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{19}
}

func (x *GetTaskStatusResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTaskStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTaskStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FillInviteCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"` // 邀请码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillInviteCodeReq) Reset() {
	*x = FillInviteCodeReq{}
	mi := &file_business_ext_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillInviteCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillInviteCodeReq) ProtoMessage() {}

func (x *FillInviteCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillInviteCodeReq.ProtoReflect.Descriptor instead.
func (*FillInviteCodeReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{20}
}

func (x *FillInviteCodeReq) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type FillInviteCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillInviteCodeResp) Reset() {
	*x = FillInviteCodeResp{}
	mi := &file_business_ext_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillInviteCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillInviteCodeResp) ProtoMessage() {}

func (x *FillInviteCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillInviteCodeResp.ProtoReflect.Descriptor instead.
func (*FillInviteCodeResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{21}
}

func (x *FillInviteCodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FillInviteCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 领取任务奖励请求
type ClaimTaskRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRewardReq) Reset() {
	*x = ClaimTaskRewardReq{}
	mi := &file_business_ext_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardReq) ProtoMessage() {}

func (x *ClaimTaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardReq.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{22}
}

func (x *ClaimTaskRewardReq) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// 领取任务奖励响应
type ClaimTaskRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRewardResp) Reset() {
	*x = ClaimTaskRewardResp{}
	mi := &file_business_ext_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRewardResp) ProtoMessage() {}

func (x *ClaimTaskRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRewardResp.ProtoReflect.Descriptor instead.
func (*ClaimTaskRewardResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{23}
}

func (x *ClaimTaskRewardResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClaimTaskRewardResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 根据推特用户名搜索用户请求
type SearchTwitterUserReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TwitterUsername string                 `protobuf:"bytes,1,opt,name=twitter_username,json=twitterUsername,proto3" json:"twitter_username,omitempty"` // 推特用户名关键字
	PageSize        int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                     // 每页数量
	PageNum         int32                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                        // 页码
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchTwitterUserReq) Reset() {
	*x = SearchTwitterUserReq{}
	mi := &file_business_ext_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTwitterUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTwitterUserReq) ProtoMessage() {}

func (x *SearchTwitterUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTwitterUserReq.ProtoReflect.Descriptor instead.
func (*SearchTwitterUserReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{24}
}

func (x *SearchTwitterUserReq) GetTwitterUsername() string {
	if x != nil {
		return x.TwitterUsername
	}
	return ""
}

func (x *SearchTwitterUserReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchTwitterUserReq) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

// 根据推特用户名搜索用户响应
type SearchTwitterUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`     // 用户列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTwitterUserResp) Reset() {
	*x = SearchTwitterUserResp{}
	mi := &file_business_ext_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTwitterUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTwitterUserResp) ProtoMessage() {}

func (x *SearchTwitterUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTwitterUserResp.ProtoReflect.Descriptor instead.
func (*SearchTwitterUserResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{25}
}

func (x *SearchTwitterUserResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchTwitterUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchTwitterUserResp) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchTwitterUserResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Token信息
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // token ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 创建者用户ID
	TokenAddress  string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // token合约地址
	TokenName     string                 `protobuf:"bytes,4,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`          // token名称
	TokenSymbol   string                 `protobuf:"bytes,5,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`    // token符号
	Decimals      int32                  `protobuf:"varint,6,opt,name=decimals,proto3" json:"decimals,omitempty"`                            // token精度
	TotalSupply   string                 `protobuf:"bytes,7,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`    // 发行总量
	CreatorAddr   string                 `protobuf:"bytes,8,opt,name=creator_addr,json=creatorAddr,proto3" json:"creator_addr,omitempty"`    // 创建者钱包地址
	ChainId       int32                  `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`               // 链ID
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                               // 状态 1:正常 0:禁用
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`        // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_business_ext_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{26}
}

func (x *Token) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Token) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Token) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Token) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Token) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *Token) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Token) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *Token) GetCreatorAddr() string {
	if x != nil {
		return x.CreatorAddr
	}
	return ""
}

func (x *Token) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Token) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Token) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Token) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建token请求
type CreateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // token合约地址
	TokenName     string                 `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`          // token名称
	TokenSymbol   string                 `protobuf:"bytes,3,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`    // token符号
	Decimals      int32                  `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`                            // token精度
	TotalSupply   string                 `protobuf:"bytes,5,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`    // 发行总量
	ChainId       int32                  `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`               // 链ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenReq) Reset() {
	*x = CreateTokenReq{}
	mi := &file_business_ext_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenReq) ProtoMessage() {}

func (x *CreateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenReq.ProtoReflect.Descriptor instead.
func (*CreateTokenReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{27}
}

func (x *CreateTokenReq) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *CreateTokenReq) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *CreateTokenReq) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *CreateTokenReq) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateTokenReq) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *CreateTokenReq) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// 创建token响应
type CreateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Token         *Token                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // token信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResp) Reset() {
	*x = CreateTokenResp{}
	mi := &file_business_ext_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResp) ProtoMessage() {}

func (x *CreateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResp.ProtoReflect.Descriptor instead.
func (*CreateTokenResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{28}
}

func (x *CreateTokenResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTokenResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTokenResp) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// 获取token请求
type GetTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // token合约地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenReq) Reset() {
	*x = GetTokenReq{}
	mi := &file_business_ext_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenReq) ProtoMessage() {}

func (x *GetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenReq.ProtoReflect.Descriptor instead.
func (*GetTokenReq) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{29}
}

func (x *GetTokenReq) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

// 获取token响应
type GetTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息描述
	Token         *Token                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`     // token信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResp) Reset() {
	*x = GetTokenResp{}
	mi := &file_business_ext_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResp) ProtoMessage() {}

func (x *GetTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_business_ext_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResp.ProtoReflect.Descriptor instead.
func (*GetTokenResp) Descriptor() ([]byte, []int) {
	return file_business_ext_proto_rawDescGZIP(), []int{30}
}

func (x *GetTokenResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTokenResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTokenResp) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_business_ext_proto protoreflect.FileDescriptor

const file_business_ext_proto_rawDesc = "" +
	"\n" +
	"\x12business.ext.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"B\n" +
	"\x19GetTwitterAuthorizeURLReq\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"p\n" +
	"\x0fWalletSignInReq\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xad\x01\n" +
	"\x10WalletSignInResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12%\n" +
	"\tuser_info\x18\x06 \x01(\v2\b.pb.UserR\buserInfo\"_\n" +
	"\x13ModifyTaskStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"D\n" +
	"\x14ModifyTaskStatusResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\tSignInReq\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x03R\bdeviceId\"R\n" +
	"\n" +
	"SignInResp\x12\x15\n" +
	"\x06is_new\x18\x01 \x01(\bR\x05isNew\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xb6\x03\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\x05R\x03sex\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05extra\x18\x05 \x01(\tR\x05extra\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"twitter_id\x18\b \x01(\tR\ttwitterId\x12)\n" +
	"\x10twitter_username\x18\t \x01(\tR\x0ftwitterUsername\x12\x16\n" +
	"\x06xpoint\x18\n" +
	" \x01(\x01R\x06xpoint\x12#\n" +
	"\rfollow_reward\x18\v \x01(\x05R\ffollowReward\x12\x1f\n" +
	"\vinvite_code\x18\f \x01(\tR\n" +
	"inviteCode\x12!\n" +
	"\finviter_code\x18\r \x01(\tR\vinviterCode\x12%\n" +
	"\x0ewallet_address\x18\x0e \x01(\tR\rwalletAddress\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"Y\n" +
	"\vGetUserResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\x04user\x18\x03 \x01(\v2\b.pb.UserR\x04user\"r\n" +
	"\rUpdateUserReq\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x02 \x01(\x05R\x03sex\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05extra\x18\x04 \x01(\tR\x05extra\"!\n" +
	"\rSearchUserReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x0eSearchUserResp\x12\x1e\n" +
	"\x05users\x18\x01 \x03(\v2\b.pb.UserR\x05users\"Y\n" +
	"\x17TwitterAuthorizeURLResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"~\n" +
	"\x10TwitterSignInReq\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\"\xe8\x01\n" +
	"\x11TwitterSignInResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12%\n" +
	"\tuser_info\x18\x06 \x01(\v2\b.pb.UserR\buserInfo\x12\x1f\n" +
	"\verr_message\x18\a \x01(\tR\n" +
	"errMessage\x12\x17\n" +
	"\aroom_id\x18\b \x01(\x03R\x06roomId\"?\n" +
	"\x0fDailySignInResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x11TwitterFollowResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\x05R\asuccess\"+\n" +
	"\x10GetTaskStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"Y\n" +
	"\x11GetTaskStatusResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"4\n" +
	"\x11FillInviteCodeReq\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"B\n" +
	"\x12FillInviteCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x12ClaimTaskRewardReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"C\n" +
	"\x13ClaimTaskRewardResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x14SearchTwitterUserReq\x12)\n" +
	"\x10twitter_username\x18\x01 \x01(\tR\x0ftwitterUsername\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x05R\apageNum\"{\n" +
	"\x15SearchTwitterUserResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x05users\x18\x03 \x03(\v2\b.pb.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\xea\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x04 \x01(\tR\ttokenName\x12!\n" +
	"\ftoken_symbol\x18\x05 \x01(\tR\vtokenSymbol\x12\x1a\n" +
	"\bdecimals\x18\x06 \x01(\x05R\bdecimals\x12!\n" +
	"\ftotal_supply\x18\a \x01(\tR\vtotalSupply\x12!\n" +
	"\fcreator_addr\x18\b \x01(\tR\vcreatorAddr\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x05R\achainId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"\xd1\x01\n" +
	"\x0eCreateTokenReq\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x02 \x01(\tR\ttokenName\x12!\n" +
	"\ftoken_symbol\x18\x03 \x01(\tR\vtokenSymbol\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\x05R\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x05 \x01(\tR\vtotalSupply\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\x05R\achainId\"`\n" +
	"\x0fCreateTokenResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x05token\x18\x03 \x01(\v2\t.pb.TokenR\x05token\"2\n" +
	"\vGetTokenReq\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\"]\n" +
	"\fGetTokenResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x05token\x18\x03 \x01(\v2\t.pb.TokenR\x05token2\xd6\a\n" +
	"\vBusinessExt\x12'\n" +
	"\x06SignIn\x12\r.pb.SignInReq\x1a\x0e.pb.SignInResp\x12*\n" +
	"\aGetUser\x12\x0e.pb.GetUserReq\x1a\x0f.pb.GetUserResp\x127\n" +
	"\n" +
	"UpdateUser\x12\x11.pb.UpdateUserReq\x1a\x16.google.protobuf.Empty\x123\n" +
	"\n" +
	"SearchUser\x12\x11.pb.SearchUserReq\x1a\x12.pb.SearchUserResp\x12T\n" +
	"\x16GetTwitterAuthorizeURL\x12\x1d.pb.GetTwitterAuthorizeURLReq\x1a\x1b.pb.TwitterAuthorizeURLResp\x12<\n" +
	"\rTwitterSignIn\x12\x14.pb.TwitterSignInReq\x1a\x15.pb.TwitterSignInResp\x12:\n" +
	"\vDailySignIn\x12\x16.google.protobuf.Empty\x1a\x13.pb.DailySignInResp\x12>\n" +
	"\rFollowTwitter\x12\x16.google.protobuf.Empty\x1a\x15.pb.TwitterFollowResp\x12<\n" +
	"\rGetTaskStatus\x12\x14.pb.GetTaskStatusReq\x1a\x15.pb.GetTaskStatusResp\x12B\n" +
	"\x0fClaimTaskReward\x12\x16.pb.ClaimTaskRewardReq\x1a\x17.pb.ClaimTaskRewardResp\x12?\n" +
	"\x0eFillInviteCode\x12\x15.pb.FillInviteCodeReq\x1a\x16.pb.FillInviteCodeResp\x129\n" +
	"\fWalletSignIn\x12\x13.pb.WalletSignInReq\x1a\x14.pb.WalletSignInResp\x12E\n" +
	"\x10ModifyTaskStatus\x12\x17.pb.ModifyTaskStatusReq\x1a\x18.pb.ModifyTaskStatusResp\x12H\n" +
	"\x11SearchTwitterUser\x12\x18.pb.SearchTwitterUserReq\x1a\x19.pb.SearchTwitterUserResp\x126\n" +
	"\vCreateToken\x12\x12.pb.CreateTokenReq\x1a\x13.pb.CreateTokenResp\x12-\n" +
	"\bGetToken\x12\x0f.pb.GetTokenReq\x1a\x10.pb.GetTokenRespB\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_business_ext_proto_rawDescOnce sync.Once
	file_business_ext_proto_rawDescData []byte
)

func file_business_ext_proto_rawDescGZIP() []byte {
	file_business_ext_proto_rawDescOnce.Do(func() {
		file_business_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_ext_proto_rawDesc), len(file_business_ext_proto_rawDesc)))
	})
	return file_business_ext_proto_rawDescData
}

var file_business_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_business_ext_proto_goTypes = []any{
	(*GetTwitterAuthorizeURLReq)(nil), // 0: pb.GetTwitterAuthorizeURLReq
	(*WalletSignInReq)(nil),           // 1: pb.WalletSignInReq
	(*WalletSignInResp)(nil),          // 2: pb.WalletSignInResp
	(*ModifyTaskStatusReq)(nil),       // 3: pb.ModifyTaskStatusReq
	(*ModifyTaskStatusResp)(nil),      // 4: pb.ModifyTaskStatusResp
	(*SignInReq)(nil),                 // 5: pb.SignInReq
	(*SignInResp)(nil),                // 6: pb.SignInResp
	(*User)(nil),                      // 7: pb.User
	(*GetUserReq)(nil),                // 8: pb.GetUserReq
	(*GetUserResp)(nil),               // 9: pb.GetUserResp
	(*UpdateUserReq)(nil),             // 10: pb.UpdateUserReq
	(*SearchUserReq)(nil),             // 11: pb.SearchUserReq
	(*SearchUserResp)(nil),            // 12: pb.SearchUserResp
	(*TwitterAuthorizeURLResp)(nil),   // 13: pb.TwitterAuthorizeURLResp
	(*TwitterSignInReq)(nil),          // 14: pb.TwitterSignInReq
	(*TwitterSignInResp)(nil),         // 15: pb.TwitterSignInResp
	(*DailySignInResp)(nil),           // 16: pb.DailySignInResp
	(*TwitterFollowResp)(nil),         // 17: pb.TwitterFollowResp
	(*GetTaskStatusReq)(nil),          // 18: pb.GetTaskStatusReq
	(*GetTaskStatusResp)(nil),         // 19: pb.GetTaskStatusResp
	(*FillInviteCodeReq)(nil),         // 20: pb.FillInviteCodeReq
	(*FillInviteCodeResp)(nil),        // 21: pb.FillInviteCodeResp
	(*ClaimTaskRewardReq)(nil),        // 22: pb.ClaimTaskRewardReq
	(*ClaimTaskRewardResp)(nil),       // 23: pb.ClaimTaskRewardResp
	(*SearchTwitterUserReq)(nil),      // 24: pb.SearchTwitterUserReq
	(*SearchTwitterUserResp)(nil),     // 25: pb.SearchTwitterUserResp
	(*Token)(nil),                     // 26: pb.Token
	(*CreateTokenReq)(nil),            // 27: pb.CreateTokenReq
	(*CreateTokenResp)(nil),           // 28: pb.CreateTokenResp
	(*GetTokenReq)(nil),               // 29: pb.GetTokenReq
	(*GetTokenResp)(nil),              // 30: pb.GetTokenResp
	(*emptypb.Empty)(nil),             // 31: google.protobuf.Empty
}
var file_business_ext_proto_depIdxs = []int32{
	7,  // 0: pb.WalletSignInResp.user_info:type_name -> pb.User
	7,  // 1: pb.GetUserResp.user:type_name -> pb.User
	7,  // 2: pb.SearchUserResp.users:type_name -> pb.User
	7,  // 3: pb.TwitterSignInResp.user_info:type_name -> pb.User
	7,  // 4: pb.SearchTwitterUserResp.users:type_name -> pb.User
	26, // 5: pb.CreateTokenResp.token:type_name -> pb.Token
	26, // 6: pb.GetTokenResp.token:type_name -> pb.Token
	5,  // 7: pb.BusinessExt.SignIn:input_type -> pb.SignInReq
	8,  // 8: pb.BusinessExt.GetUser:input_type -> pb.GetUserReq
	10, // 9: pb.BusinessExt.UpdateUser:input_type -> pb.UpdateUserReq
	11, // 10: pb.BusinessExt.SearchUser:input_type -> pb.SearchUserReq
	0,  // 11: pb.BusinessExt.GetTwitterAuthorizeURL:input_type -> pb.GetTwitterAuthorizeURLReq
	14, // 12: pb.BusinessExt.TwitterSignIn:input_type -> pb.TwitterSignInReq
	31, // 13: pb.BusinessExt.DailySignIn:input_type -> google.protobuf.Empty
	31, // 14: pb.BusinessExt.FollowTwitter:input_type -> google.protobuf.Empty
	18, // 15: pb.BusinessExt.GetTaskStatus:input_type -> pb.GetTaskStatusReq
	22, // 16: pb.BusinessExt.ClaimTaskReward:input_type -> pb.ClaimTaskRewardReq
	20, // 17: pb.BusinessExt.FillInviteCode:input_type -> pb.FillInviteCodeReq
	1,  // 18: pb.BusinessExt.WalletSignIn:input_type -> pb.WalletSignInReq
	3,  // 19: pb.BusinessExt.ModifyTaskStatus:input_type -> pb.ModifyTaskStatusReq
	24, // 20: pb.BusinessExt.SearchTwitterUser:input_type -> pb.SearchTwitterUserReq
	27, // 21: pb.BusinessExt.CreateToken:input_type -> pb.CreateTokenReq
	29, // 22: pb.BusinessExt.GetToken:input_type -> pb.GetTokenReq
	6,  // 23: pb.BusinessExt.SignIn:output_type -> pb.SignInResp
	9,  // 24: pb.BusinessExt.GetUser:output_type -> pb.GetUserResp
	31, // 25: pb.BusinessExt.UpdateUser:output_type -> google.protobuf.Empty
	12, // 26: pb.BusinessExt.SearchUser:output_type -> pb.SearchUserResp
	13, // 27: pb.BusinessExt.GetTwitterAuthorizeURL:output_type -> pb.TwitterAuthorizeURLResp
	15, // 28: pb.BusinessExt.TwitterSignIn:output_type -> pb.TwitterSignInResp
	16, // 29: pb.BusinessExt.DailySignIn:output_type -> pb.DailySignInResp
	17, // 30: pb.BusinessExt.FollowTwitter:output_type -> pb.TwitterFollowResp
	19, // 31: pb.BusinessExt.GetTaskStatus:output_type -> pb.GetTaskStatusResp
	23, // 32: pb.BusinessExt.ClaimTaskReward:output_type -> pb.ClaimTaskRewardResp
	21, // 33: pb.BusinessExt.FillInviteCode:output_type -> pb.FillInviteCodeResp
	2,  // 34: pb.BusinessExt.WalletSignIn:output_type -> pb.WalletSignInResp
	4,  // 35: pb.BusinessExt.ModifyTaskStatus:output_type -> pb.ModifyTaskStatusResp
	25, // 36: pb.BusinessExt.SearchTwitterUser:output_type -> pb.SearchTwitterUserResp
	28, // 37: pb.BusinessExt.CreateToken:output_type -> pb.CreateTokenResp
	30, // 38: pb.BusinessExt.GetToken:output_type -> pb.GetTokenResp
	23, // [23:39] is the sub-list for method output_type
	7,  // [7:23] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_business_ext_proto_init() }
func file_business_ext_proto_init() {
	if File_business_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_ext_proto_rawDesc), len(file_business_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_ext_proto_goTypes,
		DependencyIndexes: file_business_ext_proto_depIdxs,
		MessageInfos:      file_business_ext_proto_msgTypes,
	}.Build()
	File_business_ext_proto = out.File
	file_business_ext_proto_goTypes = nil
	file_business_ext_proto_depIdxs = nil
}
