// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: connect.ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageType int32

const (
	PackageType_PT_UNKNOWN        PackageType = 0 // 未知
	PackageType_PT_SIGN_IN        PackageType = 1 // 设备登录请求
	PackageType_PT_SYNC           PackageType = 2 // 消息同步触发
	PackageType_PT_HEARTBEAT      PackageType = 3 // 心跳
	PackageType_PT_MESSAGE        PackageType = 4 // 消息投递
	PackageType_PT_SUBSCRIBE_ROOM PackageType = 5 // 订阅房间
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0: "PT_UNKNOWN",
		1: "PT_SIGN_IN",
		2: "PT_SYNC",
		3: "PT_HEARTBEAT",
		4: "PT_MESSAGE",
		5: "PT_SUBSCRIBE_ROOM",
	}
	PackageType_value = map[string]int32{
		"PT_UNKNOWN":        0,
		"PT_SIGN_IN":        1,
		"PT_SYNC":           2,
		"PT_HEARTBEAT":      3,
		"PT_MESSAGE":        4,
		"PT_SUBSCRIBE_ROOM": 5,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_ext_proto_enumTypes[0].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_connect_ext_proto_enumTypes[0]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{0}
}

// 上行数据
type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PackageType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`        // 包的类型
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求id
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                             // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_connect_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetType() PackageType {
	if x != nil {
		return x.Type
	}
	return PackageType_PT_UNKNOWN
}

func (x *Input) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Input) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 下行数据
type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PackageType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PackageType" json:"type,omitempty"`        // 包的类型
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求id
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`                            // 错误码
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                       // 错误信息
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                             // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_connect_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetType() PackageType {
	if x != nil {
		return x.Type
	}
	return PackageType_PT_UNKNOWN
}

func (x *Output) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Output) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Output) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 设备登录,package_type:1
type SignInInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备id
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户id
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                        // 秘钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInInput) Reset() {
	*x = SignInInput{}
	mi := &file_connect_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInput) ProtoMessage() {}

func (x *SignInInput) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInput.ProtoReflect.Descriptor instead.
func (*SignInInput) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{2}
}

func (x *SignInInput) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SignInInput) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SignInInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 消息同步请求,package_type:2
type SyncInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 客户端已经同步的序列号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInput) Reset() {
	*x = SyncInput{}
	mi := &file_connect_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInput) ProtoMessage() {}

func (x *SyncInput) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInput.ProtoReflect.Descriptor instead.
func (*SyncInput) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{3}
}

func (x *SyncInput) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 消息同步响应,package_type:2
type SyncOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`               // 消息列表
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否有更多数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOutput) Reset() {
	*x = SyncOutput{}
	mi := &file_connect_ext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOutput) ProtoMessage() {}

func (x *SyncOutput) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOutput.ProtoReflect.Descriptor instead.
func (*SyncOutput) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{4}
}

func (x *SyncOutput) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncOutput) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 订阅房间请求
type SubscribeRoomInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 房间ID，如果为0，取消房间订阅
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                     // 消息消息序列号，
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRoomInput) Reset() {
	*x = SubscribeRoomInput{}
	mi := &file_connect_ext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRoomInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRoomInput) ProtoMessage() {}

func (x *SubscribeRoomInput) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRoomInput.ProtoReflect.Descriptor instead.
func (*SubscribeRoomInput) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRoomInput) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SubscribeRoomInput) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 投递消息回执,package_type:4
type MessageACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceAck     int64                  `protobuf:"varint,2,opt,name=device_ack,json=deviceAck,proto3" json:"device_ack,omitempty"`       // 设备收到消息的确认号
	ReceiveTime   int64                  `protobuf:"varint,3,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"` // 消息接收时间戳，精确到毫秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageACK) Reset() {
	*x = MessageACK{}
	mi := &file_connect_ext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageACK) ProtoMessage() {}

func (x *MessageACK) ProtoReflect() protoreflect.Message {
	mi := &file_connect_ext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageACK.ProtoReflect.Descriptor instead.
func (*MessageACK) Descriptor() ([]byte, []int) {
	return file_connect_ext_proto_rawDescGZIP(), []int{6}
}

func (x *MessageACK) GetDeviceAck() int64 {
	if x != nil {
		return x.DeviceAck
	}
	return 0
}

func (x *MessageACK) GetReceiveTime() int64 {
	if x != nil {
		return x.ReceiveTime
	}
	return 0
}

var File_connect_ext_proto protoreflect.FileDescriptor

const file_connect_ext_proto_rawDesc = "" +
	"\n" +
	"\x11connect.ext.proto\x12\x02pb\x1a\x11message.ext.proto\"_\n" +
	"\x05Input\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.pb.PackageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x8e\x01\n" +
	"\x06Output\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.pb.PackageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"Y\n" +
	"\vSignInInput\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x1d\n" +
	"\tSyncInput\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"P\n" +
	"\n" +
	"SyncOutput\x12'\n" +
	"\bmessages\x18\x01 \x03(\v2\v.pb.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"?\n" +
	"\x12SubscribeRoomInput\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"N\n" +
	"\n" +
	"MessageACK\x12\x1d\n" +
	"\n" +
	"device_ack\x18\x02 \x01(\x03R\tdeviceAck\x12!\n" +
	"\freceive_time\x18\x03 \x01(\x03R\vreceiveTime*s\n" +
	"\vPackageType\x12\x0e\n" +
	"\n" +
	"PT_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PT_SIGN_IN\x10\x01\x12\v\n" +
	"\aPT_SYNC\x10\x02\x12\x10\n" +
	"\fPT_HEARTBEAT\x10\x03\x12\x0e\n" +
	"\n" +
	"PT_MESSAGE\x10\x04\x12\x15\n" +
	"\x11PT_SUBSCRIBE_ROOM\x10\x05B\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_connect_ext_proto_rawDescOnce sync.Once
	file_connect_ext_proto_rawDescData []byte
)

func file_connect_ext_proto_rawDescGZIP() []byte {
	file_connect_ext_proto_rawDescOnce.Do(func() {
		file_connect_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_ext_proto_rawDesc), len(file_connect_ext_proto_rawDesc)))
	})
	return file_connect_ext_proto_rawDescData
}

var file_connect_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connect_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_connect_ext_proto_goTypes = []any{
	(PackageType)(0),           // 0: pb.PackageType
	(*Input)(nil),              // 1: pb.Input
	(*Output)(nil),             // 2: pb.Output
	(*SignInInput)(nil),        // 3: pb.SignInInput
	(*SyncInput)(nil),          // 4: pb.SyncInput
	(*SyncOutput)(nil),         // 5: pb.SyncOutput
	(*SubscribeRoomInput)(nil), // 6: pb.SubscribeRoomInput
	(*MessageACK)(nil),         // 7: pb.MessageACK
	(*Message)(nil),            // 8: pb.Message
}
var file_connect_ext_proto_depIdxs = []int32{
	0, // 0: pb.Input.type:type_name -> pb.PackageType
	0, // 1: pb.Output.type:type_name -> pb.PackageType
	8, // 2: pb.SyncOutput.messages:type_name -> pb.Message
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_connect_ext_proto_init() }
func file_connect_ext_proto_init() {
	if File_connect_ext_proto != nil {
		return
	}
	file_message_ext_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_ext_proto_rawDesc), len(file_connect_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_ext_proto_goTypes,
		DependencyIndexes: file_connect_ext_proto_depIdxs,
		EnumInfos:         file_connect_ext_proto_enumTypes,
		MessageInfos:      file_connect_ext_proto_msgTypes,
	}.Build()
	File_connect_ext_proto = out.File
	file_connect_ext_proto_goTypes = nil
	file_connect_ext_proto_depIdxs = nil
}
