// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: connect.int.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int64                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备id
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                    // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageReq) Reset() {
	*x = DeliverMessageReq{}
	mi := &file_connect_int_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageReq) ProtoMessage() {}

func (x *DeliverMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_connect_int_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageReq.ProtoReflect.Descriptor instead.
func (*DeliverMessageReq) Descriptor() ([]byte, []int) {
	return file_connect_int_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverMessageReq) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeliverMessageReq) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// 房间推送
type PushRoomMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 设备id
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`              // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomMsg) Reset() {
	*x = PushRoomMsg{}
	mi := &file_connect_int_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomMsg) ProtoMessage() {}

func (x *PushRoomMsg) ProtoReflect() protoreflect.Message {
	mi := &file_connect_int_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomMsg.ProtoReflect.Descriptor instead.
func (*PushRoomMsg) Descriptor() ([]byte, []int) {
	return file_connect_int_proto_rawDescGZIP(), []int{1}
}

func (x *PushRoomMsg) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PushRoomMsg) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// 房间推送
type PushAllMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAllMsg) Reset() {
	*x = PushAllMsg{}
	mi := &file_connect_int_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAllMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAllMsg) ProtoMessage() {}

func (x *PushAllMsg) ProtoReflect() protoreflect.Message {
	mi := &file_connect_int_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAllMsg.ProtoReflect.Descriptor instead.
func (*PushAllMsg) Descriptor() ([]byte, []int) {
	return file_connect_int_proto_rawDescGZIP(), []int{2}
}

func (x *PushAllMsg) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_connect_int_proto protoreflect.FileDescriptor

const file_connect_int_proto_rawDesc = "" +
	"\n" +
	"\x11connect.int.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11message.ext.proto\"W\n" +
	"\x11DeliverMessageReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x03R\bdeviceId\x12%\n" +
	"\amessage\x18\x02 \x01(\v2\v.pb.MessageR\amessage\"M\n" +
	"\vPushRoomMsg\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12%\n" +
	"\amessage\x18\x02 \x01(\v2\v.pb.MessageR\amessage\"3\n" +
	"\n" +
	"PushAllMsg\x12%\n" +
	"\amessage\x18\x02 \x01(\v2\v.pb.MessageR\amessage2M\n" +
	"\n" +
	"ConnectInt\x12?\n" +
	"\x0eDeliverMessage\x12\x15.pb.DeliverMessageReq\x1a\x16.google.protobuf.EmptyB\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_connect_int_proto_rawDescOnce sync.Once
	file_connect_int_proto_rawDescData []byte
)

func file_connect_int_proto_rawDescGZIP() []byte {
	file_connect_int_proto_rawDescOnce.Do(func() {
		file_connect_int_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_int_proto_rawDesc), len(file_connect_int_proto_rawDesc)))
	})
	return file_connect_int_proto_rawDescData
}

var file_connect_int_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_connect_int_proto_goTypes = []any{
	(*DeliverMessageReq)(nil), // 0: pb.DeliverMessageReq
	(*PushRoomMsg)(nil),       // 1: pb.PushRoomMsg
	(*PushAllMsg)(nil),        // 2: pb.PushAllMsg
	(*Message)(nil),           // 3: pb.Message
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_connect_int_proto_depIdxs = []int32{
	3, // 0: pb.DeliverMessageReq.message:type_name -> pb.Message
	3, // 1: pb.PushRoomMsg.message:type_name -> pb.Message
	3, // 2: pb.PushAllMsg.message:type_name -> pb.Message
	0, // 3: pb.ConnectInt.DeliverMessage:input_type -> pb.DeliverMessageReq
	4, // 4: pb.ConnectInt.DeliverMessage:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_connect_int_proto_init() }
func file_connect_int_proto_init() {
	if File_connect_int_proto != nil {
		return
	}
	file_message_ext_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_int_proto_rawDesc), len(file_connect_int_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connect_int_proto_goTypes,
		DependencyIndexes: file_connect_int_proto_depIdxs,
		MessageInfos:      file_connect_int_proto_msgTypes,
	}.Build()
	File_connect_int_proto = out.File
	file_connect_int_proto_goTypes = nil
	file_connect_int_proto_depIdxs = nil
}
