// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message.ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_MS_NORMAL MessageStatus = 0 // 正常的
	MessageStatus_MS_RECALL MessageStatus = 1 // 撤回
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MS_NORMAL",
		1: "MS_RECALL",
	}
	MessageStatus_value = map[string]int32{
		"MS_NORMAL": 0,
		"MS_RECALL": 1,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_ext_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_message_ext_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_ext_proto_rawDescGZIP(), []int{0}
}

// 单条消息投递内容（估算大约100个字节）,todo 通知栏提醒
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 推送码
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // 推送内容
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                             // 用户消息发送序列号
	SendTime      int64                  `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`   // 消息发送时间戳，精确到毫秒
	Status        MessageStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=pb.MessageStatus" json:"status,omitempty"` // 消息状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_ext_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Message) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MS_NORMAL
}

var File_message_ext_proto protoreflect.FileDescriptor

const file_message_ext_proto_rawDesc = "" +
	"\n" +
	"\x11message.ext.proto\x12\x02pb\"\x91\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTime\x12)\n" +
	"\x06status\x18\x05 \x01(\x0e2\x11.pb.MessageStatusR\x06status*-\n" +
	"\rMessageStatus\x12\r\n" +
	"\tMS_NORMAL\x10\x00\x12\r\n" +
	"\tMS_RECALL\x10\x01B\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_message_ext_proto_rawDescOnce sync.Once
	file_message_ext_proto_rawDescData []byte
)

func file_message_ext_proto_rawDescGZIP() []byte {
	file_message_ext_proto_rawDescOnce.Do(func() {
		file_message_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_ext_proto_rawDesc), len(file_message_ext_proto_rawDesc)))
	})
	return file_message_ext_proto_rawDescData
}

var file_message_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_ext_proto_goTypes = []any{
	(MessageStatus)(0), // 0: pb.MessageStatus
	(*Message)(nil),    // 1: pb.Message
}
var file_message_ext_proto_depIdxs = []int32{
	0, // 0: pb.Message.status:type_name -> pb.MessageStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_ext_proto_init() }
func file_message_ext_proto_init() {
	if File_message_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_ext_proto_rawDesc), len(file_message_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_ext_proto_goTypes,
		DependencyIndexes: file_message_ext_proto_depIdxs,
		EnumInfos:         file_message_ext_proto_enumTypes,
		MessageInfos:      file_message_ext_proto_msgTypes,
	}.Build()
	File_message_ext_proto = out.File
	file_message_ext_proto_goTypes = nil
	file_message_ext_proto_depIdxs = nil
}
