// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: push.ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushCode int32

const (
	PushCode_PC_ADD_DEFAULT         PushCode = 0
	PushCode_PC_USER_MESSAGE        PushCode = 100 // 用户消息
	PushCode_PC_GROUP_MESSAGE       PushCode = 101 // 群组消息
	PushCode_PC_ADD_FRIEND          PushCode = 110 // 添加好友请求
	PushCode_PC_AGREE_ADD_FRIEND    PushCode = 111 // 同意添加好友
	PushCode_PC_UPDATE_GROUP        PushCode = 120 // 更新群组
	PushCode_PC_ADD_GROUP_MEMBERS   PushCode = 121 // 添加群组成员
	PushCode_PC_REMOVE_GROUP_MEMBER PushCode = 122 // 移除群组成员
)

// Enum value maps for PushCode.
var (
	PushCode_name = map[int32]string{
		0:   "PC_ADD_DEFAULT",
		100: "PC_USER_MESSAGE",
		101: "PC_GROUP_MESSAGE",
		110: "PC_ADD_FRIEND",
		111: "PC_AGREE_ADD_FRIEND",
		120: "PC_UPDATE_GROUP",
		121: "PC_ADD_GROUP_MEMBERS",
		122: "PC_REMOVE_GROUP_MEMBER",
	}
	PushCode_value = map[string]int32{
		"PC_ADD_DEFAULT":         0,
		"PC_USER_MESSAGE":        100,
		"PC_GROUP_MESSAGE":       101,
		"PC_ADD_FRIEND":          110,
		"PC_AGREE_ADD_FRIEND":    111,
		"PC_UPDATE_GROUP":        120,
		"PC_ADD_GROUP_MEMBERS":   121,
		"PC_REMOVE_GROUP_MEMBER": 122,
	}
)

func (x PushCode) Enum() *PushCode {
	p := new(PushCode)
	*p = x
	return p
}

func (x PushCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushCode) Descriptor() protoreflect.EnumDescriptor {
	return file_push_ext_proto_enumTypes[0].Descriptor()
}

func (PushCode) Type() protoreflect.EnumType {
	return &file_push_ext_proto_enumTypes[0]
}

func (x PushCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushCode.Descriptor instead.
func (PushCode) EnumDescriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{0}
}

type Sender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 发送者id
	DeviceId      int64                  `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`   // 发送者设备id
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 昵称
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 头像
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`                          // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sender) Reset() {
	*x = Sender{}
	mi := &file_push_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sender) ProtoMessage() {}

func (x *Sender) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sender.ProtoReflect.Descriptor instead.
func (*Sender) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{0}
}

func (x *Sender) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Sender) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Sender) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Sender) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Sender) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// 用户消息 MC_USER_MESSAGE = 100
type UserMessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *Sender                `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 用户id或者群组id
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                          // 用户发送的消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessagePush) Reset() {
	*x = UserMessagePush{}
	mi := &file_push_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessagePush) ProtoMessage() {}

func (x *UserMessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessagePush.ProtoReflect.Descriptor instead.
func (*UserMessagePush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{1}
}

func (x *UserMessagePush) GetSender() *Sender {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *UserMessagePush) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *UserMessagePush) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// 添加好友 PC_ADD_FRIEND = 110
type AddFriendPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`   // 好友id
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`              // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFriendPush) Reset() {
	*x = AddFriendPush{}
	mi := &file_push_ext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFriendPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendPush) ProtoMessage() {}

func (x *AddFriendPush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendPush.ProtoReflect.Descriptor instead.
func (*AddFriendPush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{2}
}

func (x *AddFriendPush) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *AddFriendPush) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AddFriendPush) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *AddFriendPush) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 同意 添加好友 PC_AGREE_ADD_FRIEND = 111
type AgreeAddFriendPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`   // 好友id
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgreeAddFriendPush) Reset() {
	*x = AgreeAddFriendPush{}
	mi := &file_push_ext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgreeAddFriendPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgreeAddFriendPush) ProtoMessage() {}

func (x *AgreeAddFriendPush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgreeAddFriendPush.ProtoReflect.Descriptor instead.
func (*AgreeAddFriendPush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{3}
}

func (x *AgreeAddFriendPush) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *AgreeAddFriendPush) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AgreeAddFriendPush) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 更新群组 PC_UPDATE_GROUP = 120
type UpdateGroupPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptId         int64                  `protobuf:"varint,1,opt,name=opt_id,json=optId,proto3" json:"opt_id,omitempty"`            // 操作人用户id
	OptName       string                 `protobuf:"bytes,2,opt,name=opt_name,json=optName,proto3" json:"opt_name,omitempty"`       // 操作人昵称
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // 群组名称
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 群组头像
	Introduction  string                 `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction,omitempty"`            // 群组简介
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`                          // 附加字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupPush) Reset() {
	*x = UpdateGroupPush{}
	mi := &file_push_ext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupPush) ProtoMessage() {}

func (x *UpdateGroupPush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupPush.ProtoReflect.Descriptor instead.
func (*UpdateGroupPush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupPush) GetOptId() int64 {
	if x != nil {
		return x.OptId
	}
	return 0
}

func (x *UpdateGroupPush) GetOptName() string {
	if x != nil {
		return x.OptName
	}
	return ""
}

func (x *UpdateGroupPush) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupPush) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateGroupPush) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *UpdateGroupPush) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

// 添加群组成员 PC_AGREE_ADD_GROUPS = 121
type AddGroupMembersPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptId         int64                  `protobuf:"varint,1,opt,name=opt_id,json=optId,proto3" json:"opt_id,omitempty"`      // 操作人用户id
	OptName       string                 `protobuf:"bytes,2,opt,name=opt_name,json=optName,proto3" json:"opt_name,omitempty"` // 操作人昵称
	Members       []*GroupMember         `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`                // 群组成员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupMembersPush) Reset() {
	*x = AddGroupMembersPush{}
	mi := &file_push_ext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupMembersPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMembersPush) ProtoMessage() {}

func (x *AddGroupMembersPush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMembersPush.ProtoReflect.Descriptor instead.
func (*AddGroupMembersPush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{5}
}

func (x *AddGroupMembersPush) GetOptId() int64 {
	if x != nil {
		return x.OptId
	}
	return 0
}

func (x *AddGroupMembersPush) GetOptName() string {
	if x != nil {
		return x.OptName
	}
	return ""
}

func (x *AddGroupMembersPush) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// 删除群组成员 PC_REMOVE_GROUP_MEMBER = 122
type RemoveGroupMemberPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptId         int64                  `protobuf:"varint,1,opt,name=opt_id,json=optId,proto3" json:"opt_id,omitempty"`                           // 操作人用户id
	OptName       string                 `protobuf:"bytes,2,opt,name=opt_name,json=optName,proto3" json:"opt_name,omitempty"`                      // 操作人昵称
	DeletedUserId int64                  `protobuf:"varint,3,opt,name=deleted_user_id,json=deletedUserId,proto3" json:"deleted_user_id,omitempty"` // 被删除的成员id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberPush) Reset() {
	*x = RemoveGroupMemberPush{}
	mi := &file_push_ext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberPush) ProtoMessage() {}

func (x *RemoveGroupMemberPush) ProtoReflect() protoreflect.Message {
	mi := &file_push_ext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberPush.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberPush) Descriptor() ([]byte, []int) {
	return file_push_ext_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveGroupMemberPush) GetOptId() int64 {
	if x != nil {
		return x.OptId
	}
	return 0
}

func (x *RemoveGroupMemberPush) GetOptName() string {
	if x != nil {
		return x.OptName
	}
	return ""
}

func (x *RemoveGroupMemberPush) GetDeletedUserId() int64 {
	if x != nil {
		return x.DeletedUserId
	}
	return 0
}

var File_push_ext_proto protoreflect.FileDescriptor

const file_push_ext_proto_rawDesc = "" +
	"\n" +
	"\x0epush.ext.proto\x12\x02pb\x1a\x0flogic.ext.proto\"\x8f\x01\n" +
	"\x06Sender\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x03R\bdeviceId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\"p\n" +
	"\x0fUserMessagePush\x12\"\n" +
	"\x06sender\x18\x01 \x01(\v2\n" +
	".pb.SenderR\x06sender\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x89\x01\n" +
	"\rAddFriendPush\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"l\n" +
	"\x12AgreeAddFriendPush\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\xb0\x01\n" +
	"\x0fUpdateGroupPush\x12\x15\n" +
	"\x06opt_id\x18\x01 \x01(\x03R\x05optId\x12\x19\n" +
	"\bopt_name\x18\x02 \x01(\tR\aoptName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\"\n" +
	"\fintroduction\x18\x05 \x01(\tR\fintroduction\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\"r\n" +
	"\x13AddGroupMembersPush\x12\x15\n" +
	"\x06opt_id\x18\x01 \x01(\x03R\x05optId\x12\x19\n" +
	"\bopt_name\x18\x02 \x01(\tR\aoptName\x12)\n" +
	"\amembers\x18\x03 \x03(\v2\x0f.pb.GroupMemberR\amembers\"q\n" +
	"\x15RemoveGroupMemberPush\x12\x15\n" +
	"\x06opt_id\x18\x01 \x01(\x03R\x05optId\x12\x19\n" +
	"\bopt_name\x18\x02 \x01(\tR\aoptName\x12&\n" +
	"\x0fdeleted_user_id\x18\x03 \x01(\x03R\rdeletedUserId*\xc0\x01\n" +
	"\bPushCode\x12\x12\n" +
	"\x0ePC_ADD_DEFAULT\x10\x00\x12\x13\n" +
	"\x0fPC_USER_MESSAGE\x10d\x12\x14\n" +
	"\x10PC_GROUP_MESSAGE\x10e\x12\x11\n" +
	"\rPC_ADD_FRIEND\x10n\x12\x17\n" +
	"\x13PC_AGREE_ADD_FRIEND\x10o\x12\x13\n" +
	"\x0fPC_UPDATE_GROUP\x10x\x12\x18\n" +
	"\x14PC_ADD_GROUP_MEMBERS\x10y\x12\x1a\n" +
	"\x16PC_REMOVE_GROUP_MEMBER\x10zB\x1bZ\x19gim-xchat/pkg/protocol/pbb\x06proto3"

var (
	file_push_ext_proto_rawDescOnce sync.Once
	file_push_ext_proto_rawDescData []byte
)

func file_push_ext_proto_rawDescGZIP() []byte {
	file_push_ext_proto_rawDescOnce.Do(func() {
		file_push_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_ext_proto_rawDesc), len(file_push_ext_proto_rawDesc)))
	})
	return file_push_ext_proto_rawDescData
}

var file_push_ext_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_push_ext_proto_goTypes = []any{
	(PushCode)(0),                 // 0: pb.PushCode
	(*Sender)(nil),                // 1: pb.Sender
	(*UserMessagePush)(nil),       // 2: pb.UserMessagePush
	(*AddFriendPush)(nil),         // 3: pb.AddFriendPush
	(*AgreeAddFriendPush)(nil),    // 4: pb.AgreeAddFriendPush
	(*UpdateGroupPush)(nil),       // 5: pb.UpdateGroupPush
	(*AddGroupMembersPush)(nil),   // 6: pb.AddGroupMembersPush
	(*RemoveGroupMemberPush)(nil), // 7: pb.RemoveGroupMemberPush
	(*GroupMember)(nil),           // 8: pb.GroupMember
}
var file_push_ext_proto_depIdxs = []int32{
	1, // 0: pb.UserMessagePush.sender:type_name -> pb.Sender
	8, // 1: pb.AddGroupMembersPush.members:type_name -> pb.GroupMember
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_push_ext_proto_init() }
func file_push_ext_proto_init() {
	if File_push_ext_proto != nil {
		return
	}
	file_logic_ext_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_ext_proto_rawDesc), len(file_push_ext_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_ext_proto_goTypes,
		DependencyIndexes: file_push_ext_proto_depIdxs,
		EnumInfos:         file_push_ext_proto_enumTypes,
		MessageInfos:      file_push_ext_proto_msgTypes,
	}.Build()
	File_push_ext_proto = out.File
	file_push_ext_proto_goTypes = nil
	file_push_ext_proto_depIdxs = nil
}
